### ISSUE TITLE
Can't disable root page while still building localized pages

### ISSUE THREAD

**Issue by jeremydw** [blinkk/amagaki#111]
This doesn't work as we need it to:

```
$path: !IfEnvironment
  default: /
  prod: false  # Page is not launched in en in prod yet.
$localization:
  path: !IfEnvironment
    default: /intl/${doc.locale.id}/${doc.basename}/
    prod: /intl/${doc.locale.id}_ALL/${doc.basename}/
  locales:
    - en
    - ja
```
