### ISSUE TITLE
Path / path format plugin

### ISSUE THREAD

**Issue by jeremydw** [blinkk/amagaki#98]
Sites should be able to define their own functions used in interpolating paths.

For example:

```
$path: /posts/${doc.fields.date}/${doc.fields.slug}/
```

I should be able to:

- Define a `foo` function in `amagaki.ts`
- Use the `foo` function in the path formatter, e.g.

```
$path: /posts/${doc.fields.date}/${foo(doc.fields.slug)}/
```

**Comment by jeremydw** [comment]
Also verify usage of `!IfLocale` with the $localization setting.

```
$localization:
  path: !IfLocale
    default: /intl/${doc.locale.id}_ALL/${pod.meta.root}/${doc.basename}/
    en_uk: /intl/${doc.locale.id}/${pod.meta.root}/${doc.basename}/
    zh-CN_cn: /intl/${doc.locale.id}/${pod.meta.root}/${doc.basename}/
    zh-HK_hk: /intl/${doc.locale.id}/${pod.meta.root}/${doc.basename}/
    zh-TW_tw: /intl/${doc.locale.id}/${pod.meta.root}/${doc.basename}/
```
